# This workflow will install Python, save the PA election pages as HTMLs, and scrape results data every 15 mins
# Many thanks to this explainer: https://canovasjm.netlify.app/2020/11/29/github-actions-run-a-python-script-on-schedule-and-commit-changes/

name: Cron runner for PA Election results

on:
  schedule:
    - cron: '*/15 * * * *' # runs every 15 mins

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Execute python script
      run: |
        python ElectionScraper_PA.py
    - name: commit files
      run: |
        git config --global user.email "aseem.a.shukla@gmail.com"
        git config --global user.name "Aseem Shukla"
        git add .
        git commit -m "update data if new"
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
